
import type { Category, Product } from '@/lib/types';

export const categories: Category[] = [
  // Main Categories
  { id: 'cat-1', name: 'Large Appliances', slug: 'large-appliances' },
  { id: 'cat-2', name: 'Small Appliances', slug: 'small-appliances' },
  { id: 'cat-3', name: 'Smart Home', slug: 'smart-home' },
  { id: 'cat-4', name: 'Entertainment', slug: 'entertainment' },
  { id: 'cat-5', name: 'Offers', slug: 'offers'},

  // Subcategories for Large Appliances
  { id: 'sub-1-1', name: 'Refrigerators', slug: 'refrigerators', parent: 'large-appliances' },
  { id: 'sub-1-2', name: 'Washing Machines', slug: 'washing-machines', parent: 'large-appliances' },
  { id: 'sub-1-3', name: 'Air Conditioners', slug: 'air-conditioners', parent: 'large-appliances' },
  { id: 'sub-1-4', name: 'Ovens & Microwaves', slug: 'ovens-microwaves', parent: 'large-appliances' },

  // Subcategories for Small Appliances
  { id: 'sub-2-1', name: 'Mixer & Grinder', slug: 'mixer-grinder', parent: 'small-appliances' },
  { id: 'sub-2-2', name: 'Air Fryers', slug: 'air-fryers', parent: 'small-appliances' },
  { id: 'sub-2-3', name: 'Vacuum Cleaners', slug: 'vacuum-cleaners', parent: 'small-appliances' },
  { id: 'sub-2-4', name: 'Water Purifiers', slug: 'water-purifiers', parent: 'small-appliances' },
  { id: 'sub-2-5', name: 'Irons & Garment Steamers', slug: 'irons-steamers', parent: 'small-appliances' },
  
  // Subcategories for Smart Home
  { id: 'sub-3-1', name: 'Smart Refrigerators', slug: 'smart-refrigerators', parent: 'smart-home' },
  { id: 'sub-3-2', name: 'Smart ACs', slug: 'smart-acs', parent: 'smart-home' },
  { id: 'sub-3-3', name: 'Security Cameras', slug: 'security-cameras', parent: 'smart-home' },

  // Subcategories for Entertainment
  { id: 'sub-4-1', name: 'Smart TVs', slug: 'smart-tvs', parent: 'entertainment' },
  { id: 'sub-4-2', name: 'Soundbars & Speakers', slug: 'soundbars-speakers', parent: 'entertainment' },
  { id: 'sub-4-3', name: 'Streaming Devices', slug: 'streaming-devices', parent: 'entertainment' },
  
  // Subcategories for Offers
  { id: 'sub-5-1', name: 'Festive Sale', slug: 'festive-sale', parent: 'offers' },
  { id: 'sub-5-2', name: 'Clearance Deals', slug: 'clearance-deals', parent: 'offers' },
  { id: 'sub-5-3', name: 'Bundle Discounts', slug: 'bundle-discounts', parent: 'offers' },
];

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Samsung 253L 3-Star Double Door Refrigerator',
    description: 'A 253L double door refrigerator with Digital Inverter Technology for greater energy efficiency. Features include a convertible freezer and toughened glass shelves.',
    price: 24490,
    category: 'refrigerators',
    brand: 'Samsung',
    rating: 4.5,
    stock: 20,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Digital Inverter Compressor', 'All-around Cooling', 'Convertible Freezer', 'Toughened Glass Shelves'],
    specs: { 'Capacity': '253L', 'Energy Rating': '3 Star', 'Type': 'Double Door' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_2',
    name: 'LG 7kg 5-Star Front Load Washing Machine',
    description: 'A 7kg fully automatic front-load washing machine with 6 Motion Direct Drive technology for optimized washing. Also features a steam cycle for hygiene.',
    price: 29990,
    category: 'washing-machines',
    brand: 'LG',
    rating: 4.6,
    stock: 18,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['6 Motion DD Technology', 'Steam Cycle', 'Inverter Direct Drive Motor', 'Smart Diagnosis'],
    specs: { 'Capacity': '7kg', 'Max Spin Speed': '1200 RPM', 'Type': 'Front Load' },
    warranty: '2 Years on Product, 10 Years on Motor',
  },
  {
    id: 'prod_3',
    name: 'Philips Daily Collection Air Fryer',
    description: 'A 4.1L air fryer that lets you fry with up to 90% less fat. Patented Rapid Air technology for perfectly crispy results. Fry, bake, grill, and roast.',
    price: 8499,
    category: 'air-fryers',
    brand: 'Philips',
    rating: 4.7,
    stock: 50,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Rapid Air Technology', 'Time and Temp Control', 'Dishwasher Safe Parts', 'Recipe Booklet Included'],
    specs: { 'Capacity': '4.1L', 'Power': '1400W', 'Cord Length': '0.8m' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_4',
    name: 'Kent Grand+ RO+UV+UF Water Purifier',
    description: 'Advanced multi-stage purification with RO+UV+UF technology and TDS controller. Retains essential minerals, ensuring 100% pure and safe drinking water.',
    price: 17500,
    category: 'water-purifiers',
    brand: 'Kent',
    rating: 4.8,
    stock: 40,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Multi-stage Purification', 'Mineral RO Technology', '8L Storage Tank', 'In-tank UV Disinfection'],
    specs: { 'Technology': 'RO+UV+UF+TDS', 'Storage': '8L', 'Purification Capacity': '20 L/hr' },
    warranty: '1 Year on Product, 3 Years No-Service Charge',
  },
  {
    id: 'prod_5',
    name: 'Sony Bravia 55" 4K Ultra HD Smart TV',
    description: 'Experience stunning 4K clarity with the X1 4K Processor. Features Google TV, Dolby Audio, and a sleek, minimalist design.',
    price: 62990,
    category: 'smart-tvs',
    brand: 'Sony',
    rating: 4.9,
    stock: 15,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['4K X-Reality PRO', 'Google TV', 'Dolby Audio', 'Voice Search Remote'],
    specs: { 'Screen Size': '55 inch', 'Resolution': '3840 x 2160', 'Sound': '20W Open Baffle Speakers' },
    warranty: '1 Year Standard Warranty',
  },
  {
    id: 'prod_6',
    name: 'boAt Aavante Bar 1500',
    description: 'A 2.1 channel soundbar with a wireless subwoofer delivering 120W of immersive audio. Multiple connectivity modes including Bluetooth, AUX, and USB.',
    price: 6999,
    category: 'soundbars-speakers',
    brand: 'boAt',
    rating: 4.4,
    stock: 80,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['2.1 Channel Sound', 'Wireless Subwoofer', 'Multiple EQ Modes', 'Sleek Design'],
    specs: { 'Power Output': '120W', 'Channels': '2.1', 'Connectivity': 'HDMI(ARC), Optical, USB, AUX, Bluetooth' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_7',
    name: 'Bajaj Rex 500W Mixer Grinder',
    description: 'A powerful 500W mixer grinder with 3 stainless steel jars. Features 3-speed control and a durable, rust-proof body.',
    price: 2499,
    category: 'mixer-grinder',
    brand: 'Bajaj',
    rating: 4.3,
    stock: 150,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Powerful 500W Motor', '3 Stainless Steel Jars', '3 Speed Control', 'Overload Protection'],
    specs: { 'Power': '500W', 'Jars': '1.2L Liquidizing, 0.8L Grinding, 0.3L Chutney', 'Motor Speed': '20000 RPM' },
    warranty: '1 Year on Product, 2 Years on Motor',
  },
  {
    id: 'prod_8',
    name: 'Voltas 1.5 Ton 5-Star Inverter Split AC',
    description: 'A 1.5 Ton Split AC with an inverter compressor. Features adjustable cooling modes and an anti-dust filter for clean air.',
    price: 38990,
    category: 'air-conditioners',
    brand: 'Voltas',
    rating: 4.5,
    stock: 30,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Inverter Compressor', '4-in-1 Adjustable Mode', 'Anti-Dust Filter', 'Stabilizer Free Operation'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Refrigerant': 'R32' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_9',
    name: 'LG 28L Charcoal Convection Microwave Oven',
    description: 'This 28L convection microwave is perfect for families. Features include charcoal lighting heater, healthy heart auto cook menu, and a motorized rotisserie.',
    price: 16990,
    category: 'ovens-microwaves',
    brand: 'LG',
    rating: 4.6,
    stock: 25,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Charcoal Lighting Heater', 'Healthy Heart Auto Cook Menu', 'Motorized Rotisserie', '271 Auto Cook Menu'],
    specs: { 'Capacity': '28L', 'Type': 'Convection', 'Power': '900W' },
    warranty: '1 Year on Product, 4 Years on Magnetron',
  },
  {
    id: 'prod_10',
    name: 'Agaro Regal 800W Handheld Vacuum Cleaner',
    description: 'A compact and powerful handheld vacuum cleaner with 800W motor and 6.5 kPa suction. Comes with multiple attachments for versatile cleaning.',
    price: 1899,
    category: 'vacuum-cleaners',
    brand: 'Agaro',
    rating: 4.2,
    stock: 60,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['800W Powerful Motor', '6.5 kPa Suction', 'Lightweight & Portable', 'Multiple Attachments'],
    specs: { 'Power': '800W', 'Weight': '1.5kg', 'Cord Length': '5m' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_11',
    name: 'Philips EasySpeed Plus Steam Iron',
    description: 'This Philips steam iron makes ironing easy and effective with lots of steam to remove tough creases, a non-stick soleplate for easy gliding on all fabrics, and a Calc Clean function for durable performance.',
    price: 1999,
    category: 'irons-steamers',
    brand: 'Philips',
    rating: 4.4,
    stock: 100,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Up to 25 g/min continuous steam', '100g steam boost', 'Non-stick soleplate', 'Calc Clean slider'],
    specs: { 'Power': '2000W', 'Water tank capacity': '270ml', 'Type': 'Steam Iron' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_12',
    name: 'Samsung 657L Side-by-Side Smart Refrigerator',
    description: 'A smart refrigerator with Family Hub screen that lets you manage your groceries, connect with your family and entertain. Convertible 5-in-1 mode for flexible storage.',
    price: 85990,
    category: 'smart-refrigerators',
    brand: 'Samsung',
    rating: 4.8,
    stock: 10,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Family Hub Screen', '5-in-1 Convertible Mode', 'Twin Cooling Plus', 'SmartThings Compatible'],
    specs: { 'Capacity': '657L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi, Family Hub' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_13',
    name: 'Panasonic 1.5 Ton 5-Star Wi-Fi Inverter Smart Split AC',
    description: 'Control your AC from anywhere with the MirAie app. This smart AC features AI mode with 7-in-1 convertible cooling and voice control with Alexa and Google Assistant.',
    price: 44990,
    category: 'smart-acs',
    brand: 'Panasonic',
    rating: 4.7,
    stock: 22,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi Enabled with MirAie App', '7-in-1 Convertible Cooling', 'AI Mode', 'Voice Control'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi, Voice Assistant' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_14',
    name: 'TP-Link Tapo C200 360° 1080p Home Security Camera',
    description: 'A pan/tilt home security Wi-Fi camera with 1080p high definition video, two-way audio, and night vision up to 30 ft. Get motion detection alerts on your phone.',
    price: 2599,
    category: 'security-cameras',
    brand: 'TP-Link',
    rating: 4.5,
    stock: 90,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['1080p Full HD', 'Pan and Tilt', 'Two-Way Audio', 'Advanced Night Vision', 'Motion Detection'],
    specs: { 'Resolution': '1080p', 'Field of View': '360° horizontal, 114° vertical', 'Storage': 'MicroSD up to 128GB' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_15',
    name: 'Amazon Fire TV Stick 4K Max',
    description: 'Amazon\'s most powerful streaming stick. Features Wi-Fi 6 support, 4K Ultra HD streaming with Dolby Vision, and the Alexa Voice Remote.',
    price: 6499,
    category: 'streaming-devices',
    brand: 'Amazon',
    rating: 4.7,
    stock: 200,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi 6 Support', '4K UHD with Dolby Vision', 'Alexa Voice Remote', 'Live Picture-in-Picture view'],
    specs: { 'Resolution': 'Up to 4K Ultra HD', 'Processor': 'Quad-core 1.8GHz', 'Storage': '8GB' },
    warranty: '1-Year Limited Warranty',
  },
  {
    id: 'prod_16',
    name: 'LG 190L 4-Star Single Door Refrigerator',
    description: 'A stylish and efficient single door refrigerator with smart inverter compressor and a base stand with a drawer for extra storage of items that don\'t need cooling.',
    price: 16990,
    category: 'refrigerators',
    brand: 'LG',
    rating: 4.4,
    stock: 35,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Smart Inverter Compressor', 'Base Stand with Drawer', 'Fastest in Ice Making', 'Toughened Glass Shelves'],
    specs: { 'Capacity': '190L', 'Energy Rating': '4 Star', 'Type': 'Single Door' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_17',
    name: 'Whirlpool 7.5 kg 5-Star Top Load Washing Machine',
    description: 'Fully automatic top load washing machine with 6th Sense Technology that senses the load and adapts the wash cycle, saving water and time.',
    price: 18490,
    category: 'washing-machines',
    brand: 'Whirlpool',
    rating: 4.3,
    stock: 25,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['6th Sense Technology', 'ZPF Technology for low pressure water filling', 'Power Scrub Technology', '12 Wash Programs'],
    specs: { 'Capacity': '7.5kg', 'Max Spin Speed': '740 RPM', 'Type': 'Top Load' },
    warranty: '2 Years on Product, 10 Years on Motor',
  },
  {
    id: 'prod_18',
    name: 'Blue Star 1.2 Ton 3-Star Inverter Split AC',
    description: 'An efficient inverter split AC with a copper condenser coil for better cooling and low maintenance. Features Turbo Cool for instant cooling.',
    price: 32990,
    category: 'air-conditioners',
    brand: 'Blue Star',
    rating: 4.2,
    stock: 40,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Turbo Cool', 'Eco Mode', 'Comfort Sleep', 'Self Clean Technology'],
    specs: { 'Capacity': '1.2 Ton', 'Energy Rating': '3 Star', 'Refrigerant': 'R32' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_19',
    name: 'IFB 20L Solo Microwave Oven',
    description: 'A simple and efficient solo microwave for reheating, defrosting and cooking. Features include multi-stage cooking and auto-defrost.',
    price: 5990,
    category: 'ovens-microwaves',
    brand: 'IFB',
    rating: 4.3,
    stock: 50,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Auto Defrost', 'Multi-Stage Cooking', 'Push Button Controls', '35 Auto Cook Menu options'],
    specs: { 'Capacity': '20L', 'Type': 'Solo', 'Power': '800W' },
    warranty: '1 Year on Product, 3 Years on Magnetron & Cavity',
  },
  {
    id: 'prod_20',
    name: 'Haier 320L 3-Star Frost-Free Double Door Refrigerator',
    description: 'This Haier refrigerator comes with a Twin Inverter technology that ensures the compressor and fan can run at different speeds. It has 5-in-1 convertible modes to suit your needs.',
    price: 32490,
    category: 'refrigerators',
    brand: 'Haier',
    rating: 4.1,
    stock: 28,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Twin Inverter Technology', '5-in-1 Convertible Mode', 'Toughened Glass Shelves', 'Hour Icing Technology'],
    specs: { 'Capacity': '320L', 'Energy Rating': '3 Star', 'Type': 'Double Door' },
    warranty: '1 Year on Product, 10 Years on Compressor & Fan Motor',
  },
  {
    id: 'prod_21',
    name: 'Bosch 8kg 5-Star Front Load Washing Machine',
    description: 'A premium front load washing machine with an EcoSilence Drive motor for quiet operation and durability. Anti-Vibration side panels reduce noise.',
    price: 37990,
    category: 'washing-machines',
    brand: 'Bosch',
    rating: 4.7,
    stock: 15,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['EcoSilence Drive Motor', 'Anti-Vibration Design', 'ActiveWater Plus', 'VarioDrum'],
    specs: { 'Capacity': '8kg', 'Max Spin Speed': '1400 RPM', 'Type': 'Front Load' },
    warranty: '2 Years on Product, 12 Years on Motor',
  },
  {
    id: 'prod_22',
    name: 'Daikin 1.5 Ton 5-Star Inverter Split AC',
    description: 'High-performance AC with Neo Swing Inverter Compressor for powerful cooling. Its Coanda airflow ensures uniform cooling across the room.',
    price: 45490,
    category: 'air-conditioners',
    brand: 'Daikin',
    rating: 4.6,
    stock: 20,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Neo Swing Inverter Compressor', 'Coanda Airflow', 'PM 2.5 Filter', 'Econo Mode'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Refrigerant': 'R32' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_23',
    name: 'Samsung 23L Grill Microwave Oven',
    description: 'A stylish grill microwave oven with a ceramic enamel cavity that is durable and easy to clean. Features Browning Plus function for crispy food.',
    price: 9490,
    category: 'ovens-microwaves',
    brand: 'Samsung',
    rating: 4.4,
    stock: 30,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Browning Plus', 'Ceramic Enamel Cavity', 'Quick Defrost', 'Eco Mode'],
    specs: { 'Capacity': '23L', 'Type': 'Grill', 'Power': '800W' },
    warranty: '1 Year on Product, 10 Years on Ceramic Enamel Cavity',
  },
  {
    id: 'prod_24',
    name: 'Godrej 6.5 kg 5-Star Top Load Washing Machine',
    description: 'A durable and efficient top load washing machine with Turbo 6 Pulsator and in-built soak technology for a powerful wash.',
    price: 13990,
    category: 'washing-machines',
    brand: 'Godrej',
    rating: 4.1,
    stock: 45,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Turbo 6 Pulsator', 'In-built Soak Technology', 'Toughened Glass Lid', '5 Wash Programs'],
    specs: { 'Capacity': '6.5kg', 'Max Spin Speed': '700 RPM', 'Type': 'Top Load' },
    warranty: '2 Years on Product, 10 Years on Motor',
  },
  {
    id: 'prod_25',
    name: 'Hitachi 1.5 Ton 5-Star Inverter Split AC',
    description: 'This Hitachi AC is designed to provide intelligent cooling with its iSee technology. It expands its capacity in adverse temperature conditions and has a filter clean indicator.',
    price: 43990,
    category: 'air-conditioners',
    brand: 'Hitachi',
    rating: 4.5,
    stock: 18,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Expandable Inverter', 'iSee Technology', 'Filter Clean Indicator', 'SuperSlit Fins'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Refrigerant': 'R32' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_26',
    name: 'Preethi Zion MG-227 Mixer Grinder, 750W',
    description: 'The Preethi Zion is a powerhouse with its 750W Vega W5 motor and 5 jars for versatile kitchen needs. It can also be used for atta kneading and vegetable chopping.',
    price: 8990,
    category: 'mixer-grinder',
    brand: 'Preethi',
    rating: 4.5,
    stock: 40,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['750W Vega W5 Motor', 'Master Chef+ Jar for food processing', '3-In-1 Insta fresh Juicer Jar', 'Sturdy and durable'],
    specs: { 'Power': '750W', 'Jars': '5 (including Master Chef+ and Juicer)', 'Motor Speed': 'High RPM' },
    warranty: '2 Year on Product, 5 Years on Motor',
  },
  {
    id: 'prod_27',
    name: 'Sujata Dynamix DX Mixer Grinder, 900W',
    description: 'A heavy-duty mixer grinder with a powerful 900W motor and double ball bearings for efficiency, low maintenance and trouble-free running for years.',
    price: 5850,
    category: 'mixer-grinder',
    brand: 'Sujata',
    rating: 4.6,
    stock: 60,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Powerful 900W Motor', 'Double Ball Bearings', '3 Stainless Steel Jars', 'Vibration-free operation'],
    specs: { 'Power': '900W', 'Jars': '1 Dome jar, 2 stainless steel jars', 'Motor Speed': '22000 RPM' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_28',
    name: 'Inalsa Air Fryer Digital 4L',
    description: 'Enjoy guilt-free fried food with Inalsa Air Fryer that comes with a 4L cooking pan capacity. It features a digital display and 8 preset programs.',
    price: 5995,
    category: 'air-fryers',
    brand: 'Inalsa',
    rating: 4.3,
    stock: 55,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Digital Touch Screen', '8 Preset Programs', '4L Cooking Capacity', 'Air System Technology for less oil usage'],
    specs: { 'Capacity': '4L', 'Power': '1400W', 'Control': 'Digital' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_29',
    name: 'Havells Prolife Digi Air Fryer, 4L',
    description: 'The Havells Prolife Digi Air Fryer comes with a unique rapid air technology which makes food crispy from the outside and soft on the inside.',
    price: 9395,
    category: 'air-fryers',
    brand: 'Havells',
    rating: 4.4,
    stock: 45,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Rapid Air Technology', 'Auto On/Off', 'Air Filtration System', 'Integrated Timer with auto-off'],
    specs: { 'Capacity': '4L', 'Power': '1230W', 'Basket Size': '2L' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_30',
    name: 'Dyson V8 Absolute Cord-Free Vacuum Cleaner',
    description: 'Powerful, versatile, and low noise. The Dyson V8 Absolute is engineered for homes with pets, with whole-machine filtration to capture allergens.',
    price: 32900,
    category: 'vacuum-cleaners',
    brand: 'Dyson',
    rating: 4.8,
    stock: 25,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Cord-free, Hassle-free', 'Powered by Dyson digital motor V8', 'Two power modes', 'Transforms to a handheld'],
    specs: { 'Weight': '2.61kg', 'Run time': 'Up to 40 minutes', 'Bin volume': '0.54L' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_31',
    name: 'Eureka Forbes Quick Clean DX Vacuum Cleaner',
    description: 'A portable vacuum cleaner that is ideal for quick cleaning. It comes with a powerful 1200W motor and a range of accessories for versatile cleaning.',
    price: 3699,
    category: 'vacuum-cleaners',
    brand: 'Eureka Forbes',
    rating: 4.1,
    stock: 80,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Powerful 1200W motor', 'Dust bag full indicator', 'Automatic cord winder', '3 swivel wheels'],
    specs: { 'Power': '1200W', 'Suction Power': '1700mm of water column', 'Type': 'Canister' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_32',
    name: 'HUL Pureit Eco Water Saver Mineral RO+UV+MF',
    description: 'This Pureit water purifier provides advanced 7-stage purification and enriches water with essential minerals to provide safe and sweet drinking water. It has the highest water saving rate of up to 60%.',
    price: 13999,
    category: 'water-purifiers',
    brand: 'HUL Pureit',
    rating: 4.5,
    stock: 50,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['7-stage purification', 'Adds essential minerals', 'High water saving rate', '10L storage capacity'],
    specs: { 'Technology': 'RO+UV+MF', 'Storage': '10L', 'Purification Capacity': 'Up to 24 L/hr' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_33',
    name: 'Aquaguard Aura RO+UV+UF+Taste Adjuster Water Purifier',
    description: 'Aquaguard Aura comes with Active Copper Technology that provides goodness of copper in water and RO+UV+UF purification. The taste adjuster ensures sweet tasting water irrespective of the water source.',
    price: 11499,
    category: 'water-purifiers',
    brand: 'Aquaguard',
    rating: 4.4,
    stock: 65,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Active Copper Technology', '8 Stages of Purification', '7L storage tank', 'Can be used for TDS up to 2000ppm'],
    specs: { 'Technology': 'RO+UV+UF+Taste Adjuster (MTDS)', 'Storage': '7L', 'Boiling Point': '20 L/hr' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_34',
    name: 'Usha Aqua Glow Smart Steam Iron',
    description: 'The Usha Aqua Glow steam iron comes with a powerful steam output of up to 20gm/min for effective crease removal. It has a ceramic coated soleplate for smooth gliding.',
    price: 2199,
    category: 'irons-steamers',
    brand: 'Usha',
    rating: 4.2,
    stock: 70,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Ceramic Coated Soleplate', '2000W for quick heating', 'Vertical and Horizontal Steaming', 'Anti-drip function'],
    specs: { 'Power': '2000W', 'Water tank capacity': '300ml', 'Type': 'Steam Iron' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_35',
    name: 'Philips Handheld Garment Steamer STH3020/10',
    description: 'Compact and foldable garment steamer, for easy use and storage. Ready to use in 30 seconds, it is a perfect companion for easy and quick touch-ups at home or on the go.',
    price: 4595,
    category: 'irons-steamers',
    brand: 'Philips',
    rating: 4.6,
    stock: 50,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Compact and foldable', 'Ready in 30 seconds', '1000W with up to 20g/min continuous steam', 'No ironing board needed'],
    specs: { 'Power': '1000W', 'Water tank capacity': '120ml', 'Type': 'Garment Steamer' },
    warranty: '2 Year Warranty',
  },
    {
    id: 'prod_36',
    name: 'Prestige Delight Electric Rice Cooker Cute 1.8-2',
    description: 'Cook perfect rice every time with this Prestige electric cooker. It comes with two aluminum cooking pans and has a 1.8-litre capacity.',
    price: 2890,
    category: 'small-appliances', // A general small appliance category
    brand: 'Prestige',
    rating: 4.3,
    stock: 80,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['1.8 Litre capacity', 'Two aluminum cooking pans', 'Cool-touch handles', 'Keep warm mode'],
    specs: { 'Capacity': '1.8L', 'Power': '700W', 'Material': 'Stainless Steel' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_37',
    name: 'Wonderchef Nutri-Blend 400W Mixer-Grinder',
    description: 'Compact and powerful, this Nutri-Blend is perfect for making smoothies, juices, and grinding masalas. Comes with two interchangeable jars.',
    price: 2699,
    category: 'mixer-grinder',
    brand: 'Wonderchef',
    rating: 4.4,
    stock: 90,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Powerful 400W motor', 'Superfast 22,000 RPM', 'Surgical grade stainless steel blades', '2 unbreakable jars'],
    specs: { 'Power': '400W', 'Jars': '500ml & 300ml', 'Blades': 'Grinding and Blending' },
    warranty: '2 Year Warranty',
  },
  // New Smart Refrigerators
  {
    id: 'prod_38',
    name: 'LG 687L Frost-Free Smart Inverter Side-by-Side Refrigerator',
    description: 'This LG smart refrigerator comes with ThinQ technology, allowing you to control it from anywhere. It has a large capacity and a stylish design.',
    price: 104990,
    category: 'smart-refrigerators',
    brand: 'LG',
    rating: 4.7,
    stock: 12,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['LG ThinQ (Wi-Fi)', 'Inverter Linear Compressor', 'Multi Air Flow', 'Smart Diagnosis'],
    specs: { 'Capacity': '687L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi, Voice Assistant' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_39',
    name: 'Haier 570L Inverter Frost-Free Side-by-Side Refrigerator',
    description: 'A premium refrigerator with expert cooling technology and smart features. Connect it to your Wi-Fi and manage it through the Haier Smart Home app.',
    price: 78990,
    category: 'smart-refrigerators',
    brand: 'Haier',
    rating: 4.5,
    stock: 15,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi Connectivity', 'Deo Fresh Technology', 'Super Cool & Super Freeze Mode', '90° Door Opening'],
    specs: { 'Capacity': '570L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_40',
    name: 'Bosch 559L Frost-Free Double Door Refrigerator',
    description: 'German engineering meets smart technology. This Bosch refrigerator offers VitaFresh technology to keep food fresh for longer and can be controlled via the Home Connect app.',
    price: 72990,
    category: 'smart-refrigerators',
    brand: 'Bosch',
    rating: 4.6,
    stock: 8,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Home Connect App', 'VitaFresh Technology', 'SuperCooling', 'FreshSense sensors'],
    specs: { 'Capacity': '559L', 'Type': 'Double Door', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_41',
    name: 'Whirlpool 570L Inverter Frost-Free Multi-Door Refrigerator',
    description: 'This multi-door refrigerator offers customized temperature zones and smart connectivity. Its adaptive intelligence technology adjusts cooling based on usage patterns.',
    price: 69990,
    category: 'smart-refrigerators',
    brand: 'Whirlpool',
    rating: 4.4,
    stock: 14,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['6th Sense IntelliFresh Technology', 'Wi-Fi Connect', 'Feather Touch UI', 'Zeolite Technology'],
    specs: { 'Capacity': '570L', 'Type': 'Multi-Door', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_42',
    name: 'Godrej 564L Frost-Free Side-by-Side Refrigerator',
    description: 'A feature-packed smart refrigerator with multi-air flow system and an advanced control panel. Connect it to your home network for smart controls.',
    price: 59990,
    category: 'smart-refrigerators',
    brand: 'Godrej',
    rating: 4.3,
    stock: 20,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi Enabled', 'Multi Air Flow System', 'In-built Deodorizer', 'Customizable Temperature Settings'],
    specs: { 'Capacity': '564L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
   {
    id: 'prod_43',
    name: 'Voltas Beko 563L ProSmart Inverter Side-by-Side Refrigerator',
    description: 'This smart refrigerator from Voltas Beko features ProSmart Inverter Compressor and StoreFresh+ technology to keep your food fresh for up to 30 days.',
    price: 65990,
    category: 'smart-refrigerators',
    brand: 'Voltas Beko',
    rating: 4.4,
    stock: 18,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['ProSmart Inverter Compressor', 'StoreFresh+ Technology', 'Wi-Fi Connectivity', 'Neo Frost Dual Cooling'],
    specs: { 'Capacity': '563L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi' },
    warranty: '2 Years Comprehensive, 12 Years on Compressor',
  },
  {
    id: 'prod_44',
    name: 'Hitachi 510L Frost-Free French Door Refrigerator',
    description: 'A premium smart French door refrigerator with selectable zone, vacuum compartment, and an elegant glass door finish. Connects to the Hitachi app.',
    price: 115000,
    category: 'smart-refrigerators',
    brand: 'Hitachi',
    rating: 4.8,
    stock: 7,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi Connected', 'Vacuum Compartment', 'Selectable Zone', 'Inverter X Dual Fan Cooling'],
    specs: { 'Capacity': '510L', 'Type': 'French Door', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
   {
    id: 'prod_45',
    name: 'Blue Star 600L Smart Side-by-Side Refrigerator',
    description: 'Blue Star\'s entry into smart refrigerators with features like multi-zone cooling, touch digital display, and smart connectivity for remote management.',
    price: 75000,
    category: 'smart-refrigerators',
    brand: 'Blue Star',
    rating: 4.2,
    stock: 11,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi Enabled', 'Multi-Zone Cooling', 'Touch Digital Display', 'Super Freeze Function'],
    specs: { 'Capacity': '600L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_46',
    name: 'Panasonic 592L with ECONAVI INVERTER Side-by-Side Refrigerator',
    description: 'This smart refrigerator uses ECONAVI sensors to monitor usage patterns and optimizes cooling, saving energy. Connects to the Panasonic Smart App.',
    price: 89990,
    category: 'smart-refrigerators',
    brand: 'Panasonic',
    rating: 4.6,
    stock: 9,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['ECONAVI Inverter System', 'Panasonic Smart App Control', 'Prime Fresh+ Freezing', 'AG Clean Technology'],
    specs: { 'Capacity': '592L', 'Type': 'Side-by-Side', 'Smart Features': 'Wi-Fi, ECONAVI Sensors' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  // New Smart ACs
  {
    id: 'prod_47',
    name: 'LG 1.5 Ton 5-Star AI DUAL Inverter Wi-Fi Split AC',
    description: 'This LG AC comes with an AI Dual Inverter, Super Convertible 6-in-1 cooling, and built-in Wi-Fi for control via LG ThinQ app.',
    price: 46990,
    category: 'smart-acs',
    brand: 'LG',
    rating: 4.6,
    stock: 25,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['AI Dual Inverter', 'Super Convertible 6-in-1 Cooling', 'ThinQ (Wi-Fi)', 'HD Filter with Anti-Virus Protection'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi, AI Mode' },
    warranty: '1 Year on Product, 10 Years on Compressor with Gas Charging',
  },
  {
    id: 'prod_48',
    name: 'Samsung 1.5 Ton 5-Star Wind-Free Technology Inverter Split AC',
    description: 'Experience comfortable cooling with Samsung\'s Wind-Free technology. This smart AC can be controlled via the SmartThings app and works with Bixby.',
    price: 49990,
    category: 'smart-acs',
    brand: 'Samsung',
    rating: 4.7,
    stock: 20,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wind-Free Cooling', 'SmartThings App Control', 'AI Auto Cooling', 'Digital Inverter Boost'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi, Bixby' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_49',
    name: 'Daikin 1.5 Ton 5-Star Wi-Fi Inverter Split AC',
    description: 'This Daikin smart AC offers powerful cooling and can be controlled from anywhere using the Daikin mobile app. It features Neo Swing technology for even cooling.',
    price: 52990,
    category: 'smart-acs',
    brand: 'Daikin',
    rating: 4.5,
    stock: 18,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wi-Fi Enabled', 'Neo Swing Technology', 'PM 2.5 Filter', 'Voice control with Alexa & Google Home'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi, Voice Assistant' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_50',
    name: 'Blue Star 1.5 Ton 5-Star Smart Inverter Split AC',
    description: 'Control your AC with your voice using Blue Star\'s Smart AC technology. Features 5-in-1 convertible cooling for customized comfort.',
    price: 43490,
    category: 'smart-acs',
    brand: 'Blue Star',
    rating: 4.4,
    stock: 30,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Smart App Control', 'Voice Command Technology', '5-in-1 Convertible Cooling', 'Turbo Cool'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi, Voice Control' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_51',
    name: 'Hitachi 1.5 Ton 5-Star iKasu Smart Inverter Split AC',
    description: 'Hitachi\'s iKasu series offers smart features like auto filter clean technology and can be operated via the Hitachi Air app.',
    price: 48990,
    category: 'smart-acs',
    brand: 'Hitachi',
    rating: 4.5,
    stock: 22,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Hitachi Air App', 'iKasu Smart Technology', 'Auto Filter Clean', 'Expandable Inverter'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi' },
    warranty: '2 Years on AC, 10 Years on Compressor',
  },
  {
    id: 'prod_52',
    name: 'Voltas 1.4 Ton 5-Star Maha Adjustable Inverter Split AC',
    description: 'A smart AC from Voltas with Wi-Fi and Alexa control. Features Maha Adjustable cooling with multiple tonnage modes.',
    price: 41990,
    category: 'smart-acs',
    brand: 'Voltas',
    rating: 4.3,
    stock: 28,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Voltas Smart App', 'Works with Alexa', 'Maha Adjustable Cooling', 'High Ambient Cooling'],
    specs: { 'Capacity': '1.4 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi, Alexa' },
    warranty: '1 Year Comprehensive, 10 Years on Compressor',
  },
  {
    id: 'prod_53',
    name: 'Carrier 1.5 Ton 5-Star Flexicool Inverter Split AC',
    description: 'Carrier\'s Flexicool technology provides 4-in-1 convertible cooling. Control it smartly with the Carrier app.',
    price: 45990,
    category: 'smart-acs',
    brand: 'Carrier',
    rating: 4.4,
    stock: 26,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Flexicool Technology', 'Wi-Fi and App control', 'PM 2.5 Filter', 'Hybridjet Technology'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_54',
    name: 'Godrej 1.5 Ton 5-Star 5-in-1 Convertible Smart AC',
    description: 'This Godrej smart AC offers 5-in-1 convertible technology and connects to the Godrej Smart Life app for remote operation and diagnosis.',
    price: 39990,
    category: 'smart-acs',
    brand: 'Godrej',
    rating: 4.2,
    stock: 35,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Godrej Smart Life App', '5-in-1 Convertible Cooling', 'i-Sense Technology', 'Anti-Corrosive Blue Fins'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year on Product, 10 Years on Compressor',
  },
  {
    id: 'prod_55',
    name: 'Haier 1.5 Ton 5-Star Frost Self-Clean Inverter Smart AC',
    description: 'This Haier smart AC features self-cleaning technology and can be controlled via the Haier Smart Home app. Provides powerful cooling with its Turbo mode.',
    price: 42990,
    category: 'smart-acs',
    brand: 'Haier',
    rating: 4.3,
    stock: 24,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Frost Self-Clean Technology', 'Haier Smart Home App', 'Turbo Mode', 'Long Distance Air Throw'],
    specs: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star', 'Smart Features': 'Wi-Fi' },
    warranty: '1 Year Comprehensive, 12 Years on Compressor',
  },
  // New Security Cameras
  {
    id: 'prod_56',
    name: 'Mi 360° Home Security Camera 2K Pro',
    description: 'Offers super clear 2K image quality and a dual-axis pan-tilt-zoom motor. Features dual-band Wi-Fi and Bluetooth gateway for smart device linkage.',
    price: 4499,
    category: 'security-cameras',
    brand: 'Mi',
    rating: 4.6,
    stock: 100,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['2K Super Clear Image Quality', 'Dual-Band Wi-Fi', 'AI Human Detection', 'Two-Way Voice Calling'],
    specs: { 'Resolution': '2304 x 1296', 'Field of View': '360° horizontal', 'Storage': 'MicroSD, NAS, Cloud' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_57',
    name: 'Realme 360° Smart Security Camera 1080p',
    description: 'This smart camera from Realme supports 1080p video recording and features AI motion detection with real-time alerts.',
    price: 2999,
    category: 'security-cameras',
    brand: 'Realme',
    rating: 4.4,
    stock: 120,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['1080p WDR Video Recording', 'AI Motion Detection', 'Infrared Night Vision', 'Voice Talkback'],
    specs: { 'Resolution': '1080p', 'Field of View': '360° panoramic', 'Storage': 'MicroSD up to 128GB' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_58',
    name: 'CP Plus E27a 3MP Wi-Fi Pan & Tilt Camera',
    description: 'A reliable home security camera from CP Plus with 3MP resolution and pan/tilt functionality. View live footage on your phone via the EzyKam+ app.',
    price: 2299,
    category: 'security-cameras',
    brand: 'CP Plus',
    rating: 4.3,
    stock: 150,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['3MP Resolution', 'Pan/Tilt Function', 'EzyKam+ App', 'Motion Alert'],
    specs: { 'Resolution': '3MP', 'Field of View': '360° pan, 90° tilt', 'Storage': 'MicroSD, Cloud' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_59',
    name: 'Imou Ranger 2 360° 1080p Security Camera',
    description: 'The Imou Ranger 2 features smart tracking to automatically follow moving objects. It also has a privacy mode to hide the lens.',
    price: 2799,
    category: 'security-cameras',
    brand: 'Imou',
    rating: 4.5,
    stock: 90,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Smart Tracking', 'Privacy Mode', 'Human Detection', 'Built-in Siren'],
    specs: { 'Resolution': '1080p', 'Field of View': '355° pan, 85° tilt', 'Storage': 'MicroSD, NVR, Cloud' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_60',
    name: 'Qubo Smart Cam 360 1080p',
    description: 'Designed in India by Hero Group, this camera works with Alexa and features person detection, intruder alarm and a baby cry monitor.',
    price: 2890,
    category: 'security-cameras',
    brand: 'Qubo',
    rating: 4.4,
    stock: 80,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Person Detection', 'Intruder Alarm System', 'Baby Cry Monitor', 'Works with Alexa'],
    specs: { 'Resolution': '1080p', 'Field of View': '360° pan, 96° tilt', 'Storage': 'MicroSD, Cloud' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_61',
    name: 'TP-Link Tapo C100 1080p Wi-Fi Home Security Camera',
    description: 'A compact and affordable fixed security camera with crisp 1080p video, night vision, and motion detection.',
    price: 1899,
    category: 'security-cameras',
    brand: 'TP-Link',
    rating: 4.3,
    stock: 200,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['1080p Full HD', 'Two-Way Audio', 'Night Vision', 'Motion Detection Alerts'],
    specs: { 'Resolution': '1080p', 'Field of View': '105°', 'Storage': 'MicroSD up to 128GB' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_62',
    name: 'D-Link Full HD Wi-Fi Camera (DCS-8300LH)',
    description: 'This D-Link camera offers a wide 137° view and sound/motion detection. Cloud recording options are available with the mydlink app.',
    price: 3499,
    category: 'security-cameras',
    brand: 'D-Link',
    rating: 4.2,
    stock: 70,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['137° Wide-angle Lens', 'Sound and Motion Detection', 'Cloud Recording', 'Works with Alexa & Google Assistant'],
    specs: { 'Resolution': '1080p', 'Field of View': '137°', 'Storage': 'MicroSD, Cloud' },
    warranty: '3 Year Warranty',
  },
  {
    id: 'prod_63',
    name: 'Google Nest Cam (Battery)',
    description: 'A smart security camera from Google that can go anywhere. It\'s battery-powered and provides intelligent alerts for people, animals, and vehicles.',
    price: 16999,
    category: 'security-cameras',
    brand: 'Google',
    rating: 4.8,
    stock: 40,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Battery-powered', 'Intelligent Alerts', 'HDR and Night Vision', 'Two-way talk'],
    specs: { 'Resolution': '1080p HDR', 'Field of View': '130° diagonal', 'Storage': 'Cloud (3-hour event history included)' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_64',
    name: 'Amazon Blink Outdoor Camera',
    description: 'A wire-free, battery-powered HD security camera that helps you monitor your home day or night with infrared night vision.',
    price: 9999,
    category: 'security-cameras',
    brand: 'Amazon',
    rating: 4.5,
    stock: 60,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Wire-free', '2-year battery life', 'Two-way audio', 'Works with Alexa'],
    specs: { 'Resolution': '1080p', 'Field of View': '110° diagonal', 'Storage': 'Cloud (subscription required)' },
    warranty: '1 Year Warranty',
  },
];
