import type { Category, Product } from '@/lib/types';

export const categories: Category[] = [
  // Main Categories
  { id: 'cat-1', name: 'Large Appliances', slug: 'large-appliances' },
  { id: 'cat-2', name: 'Small Appliances', slug: 'small-appliances' },
  { id: 'cat-3', name: 'Smart Home', slug: 'smart-home' },
  { id: 'cat-4', name: 'Entertainment', slug: 'entertainment' },
  { id: 'cat-5', name: 'Offers', slug: 'offers'},

  // Subcategories for Large Appliances
  { id: 'sub-1-1', name: 'Refrigerators', slug: 'refrigerators', parent: 'large-appliances' },
  { id: 'sub-1-2', name: 'Washing Machines', slug: 'washing-machines', parent: 'large-appliances' },
  { id: 'sub-1-3', name: 'Air Conditioners', slug: 'air-conditioners', parent: 'large-appliances' },
  { id: 'sub-1-4', name: 'Ovens & Microwaves', slug: 'ovens-microwaves', parent: 'large-appliances' },

  // Subcategories for Small Appliances
  { id: 'sub-2-1', name: 'Mixer & Grinder', slug: 'mixer-grinder', parent: 'small-appliances' },
  { id: 'sub-2-2', name: 'Air Fryers', slug: 'air-fryers', parent: 'small-appliances' },
  { id: 'sub-2-3', name: 'Vacuum Cleaners', slug: 'vacuum-cleaners', parent: 'small-appliances' },
  { id: 'sub-2-4', name: 'Water Purifiers', slug: 'water-purifiers', parent: 'small-appliances' },
  { id: 'sub-2-5', name: 'Irons & Garment Steamers', slug: 'irons-steamers', parent: 'small-appliances' },
  
  // Subcategories for Smart Home
  { id: 'sub-3-1', name: 'Smart Refrigerators', slug: 'smart-refrigerators', parent: 'smart-home' },
  { id: 'sub-3-2', name: 'Smart ACs', slug: 'smart-acs', parent: 'smart-home' },
  { id: 'sub-3-3', name: 'Security Cameras', slug: 'security-cameras', parent: 'smart-home' },

  // Subcategories for Entertainment
  { id: 'sub-4-1', name: 'Smart TVs', slug: 'smart-tvs', parent: 'entertainment' },
  { id: 'sub-4-2', name: 'Soundbars & Speakers', slug: 'soundbars-speakers', parent: 'entertainment' },
  { id: 'sub-4-3', name: 'Streaming Devices', slug: 'streaming-devices', parent: 'entertainment' },
  
  // Subcategories for Offers
  { id: 'sub-5-1', name: 'Festive Sale', slug: 'festive-sale', parent: 'offers' },
  { id: 'sub-5-2', name: 'Clearance Deals', slug: 'clearance-deals', parent: 'offers' },
  { id: 'sub-5-3', name: 'Bundle Discounts', slug: 'bundle-discounts', parent: 'offers' },
];

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Aura Smart Refrigerator',
    description: 'A 300L smart refrigerator with a touch screen, voice assistant compatibility, and automatic temperature control. Keeps your food fresh and your kitchen smart.',
    price: 1299.99,
    category: 'refrigerators',
    brand: 'Aura',
    rating: 4.8,
    stock: 15,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Smart Cooling', 'Touch Screen Display', 'Voice Control', 'Ice Maker'],
    specs: { 'Capacity': '300L', 'Energy Rating': '5 Star', 'Type': 'Double Door' },
    warranty: '2 Year Comprehensive, 10 Year Compressor',
  },
  {
    id: 'prod_2',
    name: 'QuantumClean Washing Machine',
    description: 'A 8kg fully automatic front-load washing machine featuring 15 wash programs, steam cycle for hygiene, and a silent, efficient digital inverter motor.',
    price: 799.0,
    category: 'washing-machines',
    brand: 'Quantum',
    rating: 4.6,
    stock: 25,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Fully Automatic', 'Steam Cycle', 'Digital Inverter Motor', '15 Wash Programs'],
    specs: { 'Capacity': '8kg', 'Max Spin Speed': '1400 RPM', 'Type': 'Front Load' },
    warranty: '3 Year on Product, 12 Year on Motor',
  },
  {
    id: 'prod_3',
    name: 'Vortex Pro Air Fryer',
    description: 'A 5.5L digital air fryer that lets you fry, roast, bake, and grill with 95% less oil. Quick, healthy, and delicious meals are just a touch away.',
    price: 149.99,
    category: 'air-fryers',
    brand: 'Vortex',
    rating: 4.9,
    stock: 150,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['Digital Touchscreen', '8 Pre-set Programs', 'Dishwasher Safe', 'Rapid Air Technology'],
    specs: { 'Capacity': '5.5L', 'Power': '1700W', 'Temperature Range': '80-200°C' },
    warranty: '2 Year Warranty',
  },
  {
    id: 'prod_4',
    name: 'PureFlow Water Purifier',
    description: 'Advanced 7-stage RO+UV+UF water purifier that removes impurities, retains essential minerals, and provides 100% safe and pure drinking water.',
    price: 220.5,
    category: 'water-purifiers',
    brand: 'PureFlow',
    rating: 4.7,
    stock: 80,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['7-Stage Purification', 'Mineral Retention', '8L Storage Tank', 'Smart Alerts'],
    specs: { 'Technology': 'RO+UV+UF', 'Storage': '8L', 'Purification Capacity': '15 L/hr' },
    warranty: '1 Year Comprehensive',
  },
  {
    id: 'prod_5',
    name: 'EchoView 4K Smart TV',
    description: 'A 55-inch 4K UHD Smart LED TV with HDR10+, Dolby Atmos sound, and a built-in streaming platform. Experience cinematic visuals from your couch.',
    price: 999.99,
    category: 'smart-tvs',
    brand: 'EchoView',
    rating: 4.8,
    stock: 40,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['4K UHD Display', 'HDR10+', 'Dolby Atmos', 'Voice Remote'],
    specs: { 'Screen Size': '55 inch', 'Resolution': '3840 x 2160', 'Sound': '30W Speakers' },
    warranty: '1 Year Standard Warranty',
  },
  {
    id: 'prod_6',
    name: 'CineBar 5.1 Soundbar',
    description: 'A 5.1 channel soundbar with a wireless subwoofer and rear speakers. Delivers immersive, room-filling surround sound for movies, music, and games.',
    price: 450.0,
    category: 'soundbars-speakers',
    brand: 'CineBar',
    rating: 4.5,
    stock: 60,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['5.1 Surround Sound', 'Wireless Subwoofer', 'Bluetooth 5.0', 'Multiple EQ Modes'],
    specs: { 'Power Output': '400W', 'Channels': '5.1', 'Connectivity': 'HDMI, Optical, Bluetooth' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_7',
    name: 'ConnectHome Hub',
    description: 'The central hub for your smart home. Control all your compatible devices, set routines, and manage your home with a single app or voice command.',
    price: 129.0,
    category: 'smart-home',
    brand: 'ConnectHome',
    rating: 4.6,
    stock: 120,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    features: ['Universal Compatibility', 'Voice Control', 'App-based Management', 'Automated Routines'],
    specs: { 'Protocols': 'Wi-Fi, Zigbee, Z-Wave', 'Power': 'USB-C', 'Compatibility': 'Alexa, Google Assistant' },
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod_8',
    name: 'SecureEye 360 Cam',
    description: 'An AI-powered indoor security camera with 360-degree pan-tilt-zoom, night vision, and two-way audio. Keep an eye on your home from anywhere.',
    price: 89.99,
    category: 'security-cameras',
    brand: 'SecureEye',
    rating: 4.7,
    stock: 200,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    features: ['360° View', 'AI Motion Detection', 'Color Night Vision', 'Two-Way Audio'],
    specs: { 'Resolution': '1080p Full HD', 'Storage': 'Cloud & SD Card', 'Field of View': '360° Horizontal' },
    warranty: '1 Year Warranty',
  },
];
